FROM turbointegrations/base:0.1-alpine

RUN apk add --no-cache --virtual .build-deps gcc make automake g++ libxml2-dev libxslt-dev && \
    pip install pymysql && \
    pip install numpy && \
    pip install lxml && \
    pip install vmtreport && \
    apk del --no-network .build-deps
