FROM turbointegrations/base:0.1-rhel

USER 0

RUN buildDeps='gcc make automake gcc-c++ libxml2-devel libxslt-devel' && \
    yum -y install $buildDeps  && \
    pip install pymysql && \
    pip install numpy && \
    pip install lxml && \
    pip install vmtreport && \
    yum -y remove $buildDeps && \
    yum -y clean all --enablerepo='*'

USER 1001
