FROM turbointegrations/base:0.1-slim-buster

RUN buildDeps='gcc make automake g++ libxml2-dev libxslt-dev' && \
    apt-get update && \
    apt-get install $buildDeps --no-install-recommends -y && \
    rm -rf /var/lib/apt/lists/* && \
    pip install pymysql && \
    pip install numpy && \
    pip install lxml && \
    pip install vmtreport && \
    apt-get purge -y --auto-remove $buildDeps
